apiVersion: v1
kind: Service
metadata:
  name: git-checks-webserver
  labels:
    app: git-checks-webserver
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5001
  selector:
    app: git-checks-webserver
    tier: backend